[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-steputils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.5.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "google.golang.org/api"
  version = "0.21.0"

[prune]
  go-tests = true
  unused-packages = true
